repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-merge-conflict

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black
    exclude: ^src/arviz_base/example_data/

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.0.285
  hooks:
    - id: ruff
      args: [ --fix, --exit-non-zero-on-fix ]

- repo: https://github.com/MarcoGorelli/absolufy-imports
  rev: v0.3.1
  hooks:
    - id: absolufy-imports
      args: ["--never", "--application-directories", "src"]
      files: ^src/arviz_base/.+\.py$

- repo: https://github.com/MarcoGorelli/madforhooks
  rev: 0.4.1
  hooks:
    - id: no-print-statements
